### ISSUE TITLE
separate parser from layout & add build step

### ISSUE THREAD

**Issue by cataling** [adobe-webplatform/css-regions-polyfill#10]

**Comment by oslego** [comment]
Created grunt build config at 9f51a8202445e05cb9b251f381378c889a3f2a3b
Files are generated under project root at `cssregions.js` and `cssregions.min.js`

Original source has been moved from `playgrount/src/` to `src/`. Breaking it down to components coming next.

**Comment by oslego** [comment]
Done in c806e4e140cbc7f4e62235a0301abeb8447ea660
