### ISSUE TITLE
Last line justify

### ISSUE THREAD

**Issue by lpccoder** [adobe-webplatform/css-regions-polyfill#28]
I know this polyfill is a very good code but I was wondering if it's posible to get the last line of a broken (and justified) paragraph justified. Seem the polyfill inserts a [/p] and [p] to break paragraphs, Do will be posible to add an special class to get this kind of paragraphs (justified [p]) with the last (broken) line justified?
Note: [ is < and ] is >

**Comment by oslego** [comment]
The regions polyfill does not handle this. Another polyfill, [balance-text](https://github.com/adobe-webplatform/balance-text), might achieve what you want, but without the regions-like distribution of content. It's likely  that the two will interact in undesired ways.
